### ISSUE TITLE
Incompatible with ComfyUI 0.33: asset scanner API renamed (get_prefixes_for_root → get_scan_prefixes_for_root)

### ISSUE THREAD

**Issue by passiony** [DayMan84/ComfyUI-Usgromana#24]
## Bug Description

ComfyUI 0.33.0 renamed `app.assets.scanner.get_prefixes_for_root` to `get_scan_prefixes_for_root` (see `app/assets/scanner.py` line 64 in ComfyUI). Usgromana v2.0.2 still monkey-patches the old name in `utils/comfy_user_bridge.py` (`_patch_asset_scanner_prefixes`), so the plugin fails to import entirely on ComfyUI 0.33.

## Impact

The whole plugin fails to load. Because the JWT auth middleware is installed during a partial import while the login routes never get registered, the result is a lockout: every request returns `{"error": "Authentication required"}` and **nobody can log in** (admin or otherwise).

## Error

```
AttributeError: module 'app.assets.scanner' has no attribute 'get_prefixes_for_root'. Did you mean: 'get_scan_prefixes_for_root'?
[WARNING] Cannot import .../custom_nodes/ComfyUI-Usgromana-main module for custom nodes: module 'app.assets.scanner' has no attribute 'get_prefixes_for_root'
```

## Location

`utils/comfy_user_bridge.py`, `_patch_asset_scanner_prefixes()` (~lines 1386-1406):

```python
original_prefixes = asset_scanner.get_prefixes_for_root
...
def get_prefixes_for_root(root):
    ...
asset_scanner.get_prefixes_for_root = get_prefixes_for_root
```

## Suggested Fix

Use `getattr` with a fallback so it works on both pre-0.33 and 0.33+:

```python
original_prefixes = getattr(
    asset_scanner, "get_scan_prefixes_for_root",
    getattr(asset_scanner, "get_prefixes_for_root", None),
)
...
asset_scanner.get_scan_prefixes_for_root = get_scan_prefixes_for_root
asset_scanner.get_prefixes_for_root = get_scan_prefixes_for_root  # keep old name working too
```

(or simply rename to `get_scan_prefixes_for_root` if you only need to support 0.33+)

## Environment

- ComfyUI: 0.33.0 (master, commit 5ab2f7a2)
- Usgromana: v2.0.2
- OS: Ubuntu 24.04 (Docker container)

## Note

We applied the local workaround above on our deployment; filing this issue to track an upstream fix.

**Comment by DayMan84** [comment]
@passiony Thank you for pointing this out and providing detailed resolutions notes! I have included your fix in the latest 2.0.3 update.
